name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake svg

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: thehashimq
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the result to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
